### ISSUE TITLE
True Instance Count Increasing But No Visible Instances

### ISSUE THREAD

**Issue by therealnit** [MangoButtermilch/Unity-Grass-Instancer#3]
Hey!

Just pulled the indirect script and shader into a new project. Created an empty object, assigned the script, created a material for the shader with GPU Instancing on, filled out the settings and all. However, when I ran the scene, I saw that the True Instance Counter increased, but I was not able to see anything except the terrain. Do you have any ideas as to why this might be?

**Comment by MangoButtermilch** [comment]
Here are some possible issues:
- your mesh is not scaled correctly or in other words to small.
- your mesh is not correclty rotated. In my case I had to rotate my model by 90 degrees on the x axis. Maybe you have to remove/modify that line https://github.com/MangoButtermilch/Unity-Grass-Instancer/blob/914cdfd8d6c8853bd789f45d939b81fa94851157/GrassInstancerIndirect.cs#L137
also see https://github.com/MangoButtermilch/Unity-Grass-Instancer/blob/914cdfd8d6c8853bd789f45d939b81fa94851157/GrassInstancerIndirect.cs#L95
- make sure you have enabled gpu instancing on the material 
![image](https://user-images.githubusercontent.com/47949493/230772442-32491960-7517-42b8-8f47-f77d3a481f5f.png)

**Comment by therealnit** [comment]
Hi! Thanks so much for getting back to me. Sadly I'm still having the issues. I've tried with a custom grass mesh and all of the default meshes and still no luck. I also tried messing around with those two lines and removing them entirely and I also double checked that GPU instancing was enables. Sadly, still having the issue where the instance count is going up, it's just not generating the instances.

**Comment by MangoButtermilch** [comment]
What Unity version and render pipeline are you using? Also another issue could be the SRP Batcher. Unity documentation says that GPU instancing does not work with the SRP batcher https://docs.unity3d.com/Manual/GPUInstancing.html

**Comment by therealnit** [comment]
I am using URP and Unity 2021.3.21f1. I've tried multiple methods of disabling the SRP batcher: I disabled it for the project as a whole in the settings, I added a PropertyMaterialBlock to the renderer script, and I added a new material property not used in the shader buffer. With all of these, I'm still having the same issue of instance count increasing but no visible instances.
