### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by psociety** [MangoButtermilch/Unity-Grass-Instancer#6]
TY FOR CREATING THIS!!
Could you add how to use/setup instructions or a sample scene?

**Comment by MangoButtermilch** [comment]
You can find some instructions here https://github.com/MangoButtermilch/Unity-Grass-Instancer/tree/main/No%20Optimizations
I didn't write any for the new approaches but they work similiar.
Will add this to my TODOs

**Comment by psociety** [comment]
So it needs a mesh for the grass but the repo doesn't include any right? Maybe it should throw an exception if a required param is missing.
I'm not getting any error on this config while it doesn't show any grass :(
<img width="196" alt="image" src="https://github.com/user-attachments/assets/aa7f2c10-622b-41bc-a71e-eb415cabfb2a">

The mat:
<img width="196" alt="image" src="https://github.com/user-attachments/assets/50ddaabe-48f7-4862-959a-b9714c36f1cf">
